### PR TITLE
Exit the CLI with an error code if a child process errors out

### LINKED ISSUE #69: Ensure Windows & Mac machines can build Flatbread
We only test Windows and Mac support for end-users. It's important that we also know a change doesn't break platform support for development, as to not limit who can contribute to the project.

A PR including any needed fixes to get Flatbread compiling on Windows should also add Windows (and Mac) platform runners to the pipeline for the `build` stage

### LINKED ISSUE #79: If Flatbread fails with an internal error, it should exit with failure state
### Example of issue

This pipeline job succeeds incorrectly even with an internal failure:
https://github.com/FlatbreadLabs/flatbread/runs/7621079297?check_suite_focus=true#step:7:167

### PR DESCRIPTION
**Pull request by tonyketcham**
## Summary

Fixes CLI bug where child processes exiting with an error would not cause Flatbread CLI to exit with an error.

This change means errors within implementations will get caught in CI/CD.

Closes #69 
Closes #79

**Bonus feature**: Adds [bun](https://bun.sh/) as a detected runner

## Any breaking changes?

Nope

### CODE REVIEW

File: packages/flatbread/src/cli/runner.ts [hunk 1]
```diff
@@ -39,29 +39,44 @@ export default function orchestrateProcesses({
...
-          process.exit();
-        });
-      }
+    // Exit the parent process when the target process exits
+    for (let script of runningScripts) {
+      script.on('close', (code) => {
+        //
+        // If the target process exited with a non-zero `code`, exit the parent process with the same `code`
+        //
+        // If the target process closes with a null `code`, exit the parent process with an exit code of 1
```
Comment (odama626) [inline packages/flatbread/src/cli/runner.ts:58]: is ctrl+c still handled cleanly?

Comment (tonyketcham) [reply packages/flatbread/src/cli/runner.ts:58]: Yeah that behaves the same as before

**Review by odama626 — APPROVED** [review]
